### ISSUE TITLE
How to invalidate modified posts, pages, and / or products?

### ISSUE THREAD

**Issue by stefanos82** [hypeventures/woocommerce-memcached-full-page-cache#11]
First of all, congrats for continuing the amazing work of @petermolnar.

I would like to ask: how can I flush invalidated data, such as posts, pages, and / or products?

I have designed a REST API syncing mechanism to update my product data every 20 minutes or so, plus when the user wants to do so manually.

Is it possible to have something like 

![image](https://user-images.githubusercontent.com/1777466/88416100-43b0fa00-cde8-11ea-9c1c-4510ea132ec0.png)

but for product data?

I cannot give access to editors to touch WooCommerce admin settings so they can flush cache; there's a big risk to mess things up.

Any advice?

Thank you very much.

**Comment by agaleski** [comment]
Hey - Sorry I was in Holidays.
I will have a look at this and come back to you with a possibility as soon as I have the time in the next days.

**Comment by stefanos82** [comment]
@agaleski no worries, take your time.

**Comment by agaleski** [comment]
@stefanos82 Here an example on how to do it via code:
```
/**
 * Clear the cache of a product on update.
 *
 * @param int         $productId
 * @param \WC_Product $product
 *
 * @return void
 */
function example_clear_product_cache_on_rest_update ($productId = 0, $product = null) {
    \InvincibleBrands\WcMfpc\WcMfpc::getMemcached()
                                   ->clearLinks([ $product->get_permalink() => true, ]);
}

/**
 * This function runs explicitly on rest api requests.
 *
 * @return void
 */
function example_clear_page_cache_on_rest_update() {
    add_action('woocommerce_update_product', 'example_clear_product_cache_on_rest_update', 20, 2);
}

add_action('rest_api_init', 'example_clear_page_cache_on_rest_update');
```

It worked for me in local testing. If you are unable to use this code, I will think about adding this as an optional feature in Version 1.1.1 :)

**Comment by stefanos82** [comment]
Hey @agaleski thank you so much for taking the time to come up with a possible solution.

I will test it and will let you know.

Thank you for once again mate :+1:

**Comment by stefanos82** [comment]
I think I didn't make myself clear about the REST API; my apologies.

The products are not only updated / synchronized from REST API, but also can be updated from WP's dashboard as well, so it's not only a REST API thing; it's a standard edit / update WP behavior when you click on either "Publish" or "Update" on a product page.

I have also noticed that using memcached affects my whole website's behavior, plus most of my Ajax code in various plugins and theme parts, such as mini cart and increasing or decreasing product quantity does not synchronize with checkout page.

I will experiment though even more and see how ti goes.

Thanks again.

**Comment by agaleski** [comment]
If you have any further questions, let me know :+1:
